---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgupgrades.crunchydata.com
spec:
  group: crunchydata.com
  names:
    kind: Pgupgrade
    listKind: PgupgradeList
    plural: pgupgrades
    singular: pgupgrade
  scope: Namespaced
  version: v1
