---
- name: Get Namespace Detail
  shell: "kubectl get namespace {{ kubernetes_namespace }}"
  register: namespace_details
  ignore_errors: yes
  tags: deprovision

- name: Create PostgreSQL Operator Kubernetes Project
  shell: "kubectl create namespace {{ kubernetes_namespace }}"
  when: namespace_details.rc != 0
  tags: deprovision

- name: Set namespace
  set_fact:
    namespace: "{{ kubernetes_namespace }}"
  tags: deprovision
