---
- name: Get Project Detail
  shell: "{{ openshift_oc_bin }} get project {{ openshift_project }}"
  register: project_details
  ignore_errors: yes

- name: Create PostgreSQL Operator Openshift Project
  shell: "{{ openshift_oc_bin }} new-project {{ openshift_project }}"
  when: project_details.rc != 0

- name: Set namespace
  set_fact:
    namespace: "{{ openshift_project }}"
